export const words = [
    { value: 'мечка', description: 'Голямо горско животно' },
    { value: 'дърво', description: 'Голямо растение с корен, ствол и клони' },
    { value: 'вятър', description: 'Движение на въздуха' },
    { value: 'врата', description: 'Част от входа на стая или къща' },
    { value: 'риба', description: 'Животно, което живее във вода' },
    { value: 'слънце', description: 'Звездата, която свети денем' },
    { value: 'лодка', description: 'Малък плавателен съд' },
    { value: 'река', description: 'Течение от вода' },
    { value: 'зима', description: 'Студеният сезон на годината' },
    { value: 'лято', description: 'Топлият сезон на годината' },
    { value: 'ябълка', description: 'Червен или зелен сладък плод' },
    { value: 'балон', description: 'Играчка, която се пълни с въздух' },
    { value: 'цвете', description: 'Растение с красиви цветове' },
    { value: 'книга', description: 'Предмет, в който има написан текст' },
    { value: 'пчела', description: 'Насекомо, което прави мед' },
    { value: 'конче', description: 'Малък кон' },
    { value: 'пясък', description: 'Ситни зърна по плажа или в пустинята' },
    { value: 'гора', description: 'Място с много дървета' },
    { value: 'ключ', description: 'Предмет за отключване на врата' },
    { value: 'облак', description: 'Събира пара и носи дъжд' },
    { value: 'мост', description: 'Съоръжение за преминаване над река' },
    { value: 'куче', description: 'Домашен любимец, който лае' },
    { value: 'котка', description: 'Домашен любимец, който мяука' },
    { value: 'нощ', description: 'Времето, когато е тъмно' },
    { value: 'ден', description: 'Времето, когато е светло' },
    { value: 'топка', description: 'Играчка за ритане или хвърляне' },
    { value: 'море', description: 'Голяма солена вода' },
    { value: 'къща', description: 'Място, където живеем' },
    { value: 'влак', description: 'Превозно средство по релси' },
    { value: 'кола', description: 'Превозно средство с четири гуми' },
    { value: 'баба', description: 'Майката на мама или тате' },
    { value: 'дядо', description: 'Бащата на мама или тате' },
    { value: 'пате', description: 'Малка патица' },
    { value: 'птица', description: 'Животно с крила' },
    { value: 'сняг', description: 'Бели кристали, които падат зимата' },
    { value: 'мляко', description: 'Бяла напитка от крави' },
    { value: 'хляб', description: 'Основна храна от брашно' },
    { value: 'сол', description: 'Бяла подправка' },
    { value: 'мед', description: 'Сладка храна от пчели' },
    { value: 'чаша', description: 'Съд за пиене' },
    { value: 'вода', description: 'Напитка без цвят и вкус' },
    { value: 'торта', description: 'Сладък десерт за празник' },
    { value: 'сирене', description: 'Млечен продукт' },
    { value: 'масло', description: 'Мазнина от мляко' },
    { value: 'лимон', description: 'Кисел жълт плод' },
    { value: 'малина', description: 'Червен горски плод' },
    { value: 'грозде', description: 'Плод на чепки' },
    { value: 'банан', description: 'Жълт сладък плод' },
    { value: 'ягода', description: 'Червен сладък плод' },
    { value: 'череша', description: 'Червен дребен плод' },
    { value: 'праскова', description: 'Космат сладък плод' },
    { value: 'крава', description: 'Животно, което дава мляко' },
    { value: 'овца', description: 'Животно, което дава вълна' },
    { value: 'коза', description: 'Животно, което блее' },
    { value: 'петел', description: 'Птица, която кукурига' },
    { value: 'прасе', description: 'Животно, което грухти' },
    { value: 'мишка', description: 'Малък гризач' }
]
